import { table, autoGeneratedHashKey, attribute, hashKey } from '@aws/dynamodb-data-mapper-annotations';
   
@table('pazienti')
export class Paziente {
    
    @autoGeneratedHashKey()
    @hashKey({
        indexKeyConfigurations:{
            ItemIdIndex: 'HASH'
        }
    })
    id?: string;

    @attribute()
    nome: string;

    @attribute()
    cognome: string;

    @attribute()
    email: string;

    @attribute()
    password: string;
};