import { table, autoGeneratedHashKey, attribute, hashKey } from '@aws/dynamodb-data-mapper-annotations';
import { RuoloSanitario } from './ruoloSanitario';
   
@table('sanitari')
export class Sanitario {
    
    @autoGeneratedHashKey()
    @hashKey({
        indexKeyConfigurations:{
            ItemIdIndex: 'HASH'
        }
    })
    id: string;

    @attribute()
    nome: string;

    @attribute()
    cognome: string;

    @attribute()
    ruolo: RuoloSanitario;

    @attribute()
    email: string;

    @attribute()
    password: string;
};